### ISSUE TITLE
Optimized Config

### ISSUE THREAD

**Issue by Godl1nk** [SparklyPower/SparklyPaper#37]
do you guys mind releasing good config preset that we Survival server owners can plug and play ? since u guys are a big server and is confirmed to be more experienced.

please

**Comment by MrPowerGamerBR** [comment]
```yml
config-version: 2
parallel-world-ticking:
  threads: 8
world-settings:
  "default":
    skip-map-item-data-updates-if-map-does-not-have-craftmaprenderer: true
    blazingly-simple-farm-checks:
      enabled: true
      default-growth-speed: 1.0
      moist-growth-speed: 5.0
      skip-middle-aging-stages-for-crops: true
    ticks-per:
      hopper-cooldown-when-target-container-is-full: 16
```

This is what I use on my server, but you need to tune according to your needs
